### ISSUE TITLE
Add UnoTelly as an VPN server

### ISSUE THREAD

**Issue by kimme** [Zomboided/repository.zomboided.plugins#1]
UnoTelly has an OpenVPN service that I use succesfully with Linux Mint 18 and woukld love to have UnoTelly added as an pre-configured service...

More info here...

http://help.unotelly.com/support/solutions/articles/184300-openvpn-info-and-files-please-read-

**Comment by Zomboided** [comment]
I've added it to the list of futures for VPN Manager, but this has nothing to do with my Kodi repo...
