### ISSUE TITLE
VPN Manager failed to connect to PIA 

### ISSUE THREAD

**Issue by fhenry6** [Zomboided/repository.zomboided.plugins#3]
Hi - I have been trying to establish a connection to various PIA servers and none of them are successful. 

I am getting a 

ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory 

Please help.

**Comment by fhenry6** [comment]
More details 

Openelec Version - 8.0
Kodi - 17.1

Issue resolved after doing 

mkdir /dev/net
mknod /dev/net/tun c 10 200
chmod 0666 /dev/net/tun

**Comment by Zomboided** [comment]
What platform was this on?
Looks like an issue with OE rather than my add-on. From what you've said openvpn would have failed on the command line. Might be worth mentioning it on the OE forum if they think they're supporting openvpn
