### ISSUE TITLE
OpenVpn on kodi 17.5 OSMC

### ISSUE THREAD

**Issue by ibizatiger** [Zomboided/repository.zomboided.plugins#5]
Hello, 

I have the following problem

Since fresh install OSMC kodi krypton 17.5, OpenVpn keeps failing to connect to IPvanish server. Authentification error / cert and keys 
--> i tripple checked login and password so that is not the issue
what about certs and keys? were can i check or add those

worked fine on openelec kodi 17.3

thx in advance 

ps i'm very new @ all this... appreciate your help

**Comment by Zomboided** [comment]
In setting/utilities you can clear the downloaded files, clear the vpn provider files and clear the keys/certs. Then you can re-add them. If it worked previously then it's likely to be either a problem with the network not being able to authenticate or it's an issue with what you're providing to authenticate. You can also look on the wiki on the trouble shooting page, and look at the vpn log. And maybe it's worth looking at the install page in case you've not set it up right for a Linux install

**Comment by ibizatiger** [comment]
thx for your quick reply!

i went to settings / utilities but there were no provider files for IPvanish
IPvanish is not listed 
 . 
i re-checked username and passw. ( OK )

i did, discribed in tutorial, the installation for openvpn ( sudo apt-get install openvpn ( ssh) )

in the network nothing changed. ipvanish works fine on my pc in same LAN
gone take a look in the wiki page

![20171120_105147](https://user-images.githubusercontent.com/33783708/33014493-ce704f8c-cde7-11e7-9d25-46d57e8d9049.jpg)

i uploaded the vpn log if this can help 

thx for your help

**Comment by Zomboided** [comment]
This says auth failed - you're not supplying something you should be
correctly.  I don't use IP Vanish, but many others do without issue.  Try
checking out the support docs on the IP Vanish website for how to set up
Linux manually. All this addon is doing is fronting that process.

**Comment by ibizatiger** [comment]
Thx for the reply...
I did installation + connection trough SSH. It worked immediately. I checked again in GUI, same settings/credentials appeard... Only the remote control yatse, alway added a blanc space at the and of username and passw - - > that was not visible in settings GUI.
So problem solved... 

Thx for the support!
