### ISSUE TITLE
Could not connecto to repository

### ISSUE THREAD

**Issue by darzu84** [Zomboided/repository.zomboided.plugins#8]
Hello,

i transferred the repository to my libreelec kodi installation, installed manually the repository. When i try to access the repository to install the addon it gives me the error with the error message "Could not connect to repository."

Thanks

Ervin

**Comment by Zomboided** [comment]
If you’re using kodi 11 it won’t work, there’s a defect open. If you’re on 10, share a log and I’ll take a look

**Comment by darzu84** [comment]
Hello,

sorry it was my bad, i had some connection issues on my rpi2 btw i am using kodi 19.4 and the repository id working.
