### ISSUE TITLE
Connecting to openvpn server

### ISSUE THREAD

**Issue by darzu84** [Zomboided/repository.zomboided.plugins#9]
Hello,

there is a way to use this addon to connect to another openvpn server? i got at home a running openvpn server running from my windows box and openvpn client i am able to connect to my openvpn server, i got this addon running on a rpi 2 using the libreelec distro, i would like to connect to my home network whenever i open kodi.
There is a way to do this?

Thanks

**Comment by Zomboided** [comment]
Yes, use User Defined.  There's a wizard that tries to suck in the ovpn files and do what it needs, but sometimes this needs intervention.  The wiki talks to this.
If you're using a key with a password, the wizard will fail, this is a known bug I've no energy to fix.

**Comment by darzu84** [comment]
Yes i have an ovpn profile which can be imported, it works under windows/android using the openvpn client, but i have username and password also, it is not an issue to insert it, i will try it again today and search for the wiki also. Maybe if you could help me with a link from the wiki?

Thanks

**Comment by Zomboided** [comment]
https://github.com/Zomboided/service.vpn.manager/wiki
